### ISSUE TITLE
Running lein dev on the examples gives an exception

### ISSUE THREAD

**Issue by juliangamble** [jarohen/chord#38]
When running `lein dev` on the `example-project`, I get the following exception. 

```java
SEVERE: Error compiling CLJS...
clojure.lang.ExceptionInfo: failed compiling file:ui-src/chord/example/front_end.cljs {:file #object[java.io.File 0x44e4c991 "ui-src/chord/example/front_end.cljs"]}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at cljs.compiler$compile_file$fn__11304.invoke(compiler.cljc:1146)
	at cljs.compiler$compile_file.invoke(compiler.cljc:1109)
	at cljs.compiler$compile_root.invoke(compiler.cljc:1181)
	at cljs.closure$compile_dir.invoke(closure.clj:385)
	at cljs.closure$eval11670$fn__11671.invoke(closure.clj:425)
	at cljs.closure$eval11623$fn__11624$G__11614__11631.invoke(closure.clj:331)
	at cljs.closure$eval11683$fn__11684.invoke(closure.clj:439)
	at cljs.closure$eval11623$fn__11624$G__11614__11631.invoke(closure.clj:331)
	at yoyo.cljs$compile_cljs_BANG_$reify__12087$fn__12088.invoke(cljs.clj:55)
	at clojure.core$map$fn__4553.invoke(core.clj:2622)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4128.invoke(core.clj:137)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$mapcat.doInvoke(core.clj:2660)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at yoyo.cljs$compile_cljs_BANG_$reify__12087._compile(cljs.clj:55)
	at cljs.closure$build.invoke(closure.clj:1476)
	at yoyo.cljs$compile_cljs_BANG_$fn__12091.invoke(cljs.clj:61)
	at yoyo.cljs$compile_cljs_BANG_.invoke(cljs.clj:60)
	at yoyo.cljs$watch_cljs_BANG_.invoke(cljs.clj:90)
	at yoyo.cljs$with_cljs_compiler.invoke(cljs.clj:142)
	at chord.example.main$with_cljs_compiler.invoke(main.clj:31)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at yoyo.system$make_system$fn__30294$fn__30295$fn__30296.invoke(system.clj:37)
	at yoyo.system$make_system$fn__30294$fn__30295$fn__30296$fn__30300.invoke(system.clj:39)
	at yoyo.system$constant_value$fn__30262.invoke(system.clj:8)
	at yoyo.system$make_system$fn__30294$fn__30295$fn__30296.invoke(system.clj:37)
	at yoyo.system$make_system$fn__30294.invoke(system.clj:44)
	at yoyo.system$with_system_put_to$fn__30330.invoke(system.clj:57)
	at clojure.lang.Var.invoke(Var.java:379)
	at yoyo$run_system_BANG_$fn__28808.invoke(yoyo.clj:46)
	at clojure.core$binding_conveyor_fn$fn__4444.invoke(core.clj:1916)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: clojure.lang.ExceptionInfo: No such namespace: chord.http, could not locate chord/http.cljs, chord/http.cljc, or Closure namespace "chord.http" at line 1 ui-src/chord/example/front_end.cljs {:file "ui-src/chord/example/front_end.cljs", :line 1, :column 1, :tag :cljs/analysis-error}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at cljs.analyzer$error.invoke(analyzer.cljc:384)
	at cljs.analyzer$error.invoke(analyzer.cljc:382)
	at cljs.analyzer$analyze_deps.invoke(analyzer.cljc:1293)
	at cljs.analyzer$eval9926$fn__9928.invoke(analyzer.cljc:1545)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:1900)
	at cljs.analyzer$analyze$fn__10176.invoke(analyzer.cljc:1992)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:1985)
	at cljs.compiler$compile_file_STAR_$fn__11272.invoke(compiler.cljc:1027)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:968)
	at cljs.compiler$compile_file_STAR_.invoke(compiler.cljc:988)
	at cljs.compiler$compile_file$fn__11304.invoke(compiler.cljc:1129)
	... 41 more
```

I'll submit a pull request for a fix now.

**Comment by jarohen** [comment]
Thanks again @juliangamble :)
